// <auto-generated />
using System;
using MLZ_Sefer_Xheladini.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MLZ_Sefer_Xheladini.Migrations
{
    [DbContext(typeof(MLZ_Sefer_XheladiniContext))]
    partial class MLZ_Sefer_XheladiniContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MLZ_Sefer_Xheladini.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BedCount");

                    b.Property<int?>("BuildingTypeId");

                    b.Property<string>("City");

                    b.Property<string>("Condition");

                    b.Property<bool>("HasBalkony");

                    b.Property<bool>("HasParking");

                    b.Property<bool>("HasWlan");

                    b.Property<int>("ImageId");

                    b.Property<bool>("IsActive");

                    b.Property<double>("ParkingPrice");

                    b.Property<double>("PricePerDay");

                    b.Property<double>("Space");

                    b.Property<string>("Title");

                    b.Property<int>("UserId");

                    b.Property<double>("WlanPrice");

                    b.Property<string>("ZipCode");

                    b.HasKey("BuildingId");

                    b.HasIndex("BuildingTypeId");

                    b.HasIndex("ImageId");

                    b.HasIndex("UserId");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("MLZ_Sefer_Xheladini.Models.BuildingType", b =>
                {
                    b.Property<int>("BuildingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type");

                    b.HasKey("BuildingTypeId");

                    b.ToTable("BuildingType");
                });

            modelBuilder.Entity("MLZ_Sefer_Xheladini.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BuildingId");

                    b.Property<byte[]>("Content");

                    b.Property<string>("ContentType");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ImageId");

                    b.HasIndex("BuildingId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("MLZ_Sefer_Xheladini.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<string>("Password");

                    b.Property<int?>("UserTypeId");

                    b.HasKey("UserId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MLZ_Sefer_Xheladini.Models.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("MLZ_Sefer_Xheladini.Models.Building", b =>
                {
                    b.HasOne("MLZ_Sefer_Xheladini.Models.BuildingType", "BuildingType")
                        .WithMany()
                        .HasForeignKey("BuildingTypeId");

                    b.HasOne("MLZ_Sefer_Xheladini.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MLZ_Sefer_Xheladini.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MLZ_Sefer_Xheladini.Models.Image", b =>
                {
                    b.HasOne("MLZ_Sefer_Xheladini.Models.Building")
                        .WithMany("ImageList")
                        .HasForeignKey("BuildingId");
                });

            modelBuilder.Entity("MLZ_Sefer_Xheladini.Models.User", b =>
                {
                    b.HasOne("MLZ_Sefer_Xheladini.Models.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
